services:
  # go-chi-boilerplate:
  #   image: go-chi-boilerplate:latest
  #   build:
  #     context: .
  #     dockerfile: Containerfile
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   environment:
  #     - PORT=8080
  #     - LOG_LEVEL=info
  #     - SERVICE_NAME=chi-boilerplate
  #     - OTLP_ENDPOINT=otel-collector:4317
  #     # Database connection
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USER=appuser
  #     - DB_PASSWORD=apppassword
  #     - DB_NAME=appdb
  #     - DB_SSLMODE=disable
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
