services:
  go-chi-boilerplate:
    image: go-chi-boilerplate:latest
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - SERVICE_NAME=go-chi-boilerplate
      - OTLP_ENDPOINT=otel-collector:4317
      # Database connection
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_NAME=appdb
      - DB_SSLMODE=disable
      # Redis connection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis!password123
      - REDIS_DB=0
      - REDIS_PREFIX=go-chi-boilerplate
      - REDIS_TTL=1h # supports values like 15m, 1h
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "redis!password123"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
