name: Build and Test

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "deployment/**"
      - ".github/**"
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install Dependencies
        run: |
          go mod download

      - name: Install swag CLI
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$GOPATH/bin" >> $GITHUB_PATH

      - name: Generate Swagger Docs
        run: |
          swag init -g cmd/api/main.go -o docs

      - name: Build Go Binary
        run: |
          go build -ldflags="-s -w" -o app ./cmd/api

      - name: Build Docker Image
        run: |
          docker build -t go-chi-app:latest -f Containerfile .

      - name: Test Docker Image
        run: |
          docker run --rm -d --name go-chi-app -p 8080:8080 go-chi-app:latest
          sleep 5
          curl -f http://localhost:8080/system/health
          docker stop go-chi-app
